### ISSUE TITLE
如果跑bert-base模型，需要改哪些地方

### ISSUE THREAD

**Issue by fuyuer233** [zhangfan-tju/Datawhale-Tianchi-NLP-Tutorial#1]
如果跑bert-base模型，i需要改哪些地方

**Comment by zhangfanTJU** [comment]
本次比赛的数据是匿名id，如果希望使用更重的模型，需要重新预训练。
预训练需要在config里指定模型的超参数，如层数，隐藏层大小等，具体细节可以参考预训练的代码。
代码与预训练模型已经一同开源。
