### ISSUE TITLE
RuntimeError: shape '[16, 2, 256]' is invalid for input of size 24576

### ISSUE THREAD

**Issue by mediocre-Lin** [zhangfan-tju/Datawhale-Tianchi-NLP-Tutorial#2]
你好，我训练了一个bert- large，将其用于天池上的代码时，发生下面的错误，请问大佬应该如何修改？

RuntimeError                              Traceback (most recent call last)
<ipython-input-34-ab20ad4f465a> in <module>()
      1 # train
      2 trainer = Trainer(model, vocab)
----> 3 trainer.train()
      4 # test
      5 trainer.test()

3 frames
<ipython-input-33-fa0ab0d48c52> in train(self)
     43         logging.info('Start training...')
     44         for epoch in range(1, epochs + 1):
---> 45             train_f1 = self._train(epoch)
     46 
     47             dev_f1 = self._eval(epoch)

<ipython-input-33-fa0ab0d48c52> in _train(self, epoch)
     81             torch.cuda.empty_cache()
     82             batch_inputs, batch_labels = self.batch2tensor(batch_data)
---> 83             batch_outputs = self.model(batch_inputs)
     84             loss = self.criterion(batch_outputs, batch_labels)
     85             loss.backward()

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

<ipython-input-28-c49d941fd266> in forward(self, batch_inputs)
     42         sent_reps = self.word_encoder(batch_inputs1, batch_inputs2)  # sen_num x sent_rep_size
     43 
---> 44         sent_reps = sent_reps.view(batch_size, max_doc_len, self.sent_rep_size)  # b x doc_len x sent_rep_size
     45         batch_masks = batch_masks.view(batch_size, max_doc_len, max_sent_len)  # b x doc_len x max_sent_len
     46         sent_masks = batch_masks.bool().any(2).float()  # b x doc_len

RuntimeError: shape '[16, 2, 256]' is invalid for input of size 24576

**Comment by zhangfanTJU** [comment]
24576 = 16 * 2 * 768，所以问题出在44处view时的shape。
只需要将self.sent_rep_size修改为768即可，具体位置如下：
https://github.com/zhangfanTJU/Datawhale-Tianchi-NLP-Tutorial/blob/master/src/model.py#L12
欢迎贡献bert-large~
